language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install python-coveralls
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
after_success:
  - coveralls   # uploads reports to coveralls.io
before_deploy:
  - pip install -r deploy-requirements.txt
#  - python setup.py bdist_wheel  # this runs automatically
deploy:
  provider: pypi
  user: PYPI_USER
  password: PYPI_PW
  distributions: "sdist bdist_wheel"
#  skip_existing: true  # used since two python versions
  on:
#    tags: true
    branch: master  # this is default anyway